#!/usr/bin/env node

// Setup script for Tunnl.ai Extension environment variables
// This script helps developers set up their .env file

const fs = require('fs');
const path = require('path');
const readline = require('readline');

const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
});

console.log('🔧 Tunnl.ai Extension Environment Setup');
console.log('=====================================\n');

// Check if .env file already exists
const envPath = path.join(__dirname, '.env');
const envExists = fs.existsSync(envPath);

if (envExists) {
    console.log('📄 .env file already exists');
    rl.question('Do you want to update it? (y/N): ', (answer) => {
        if (answer.toLowerCase() === 'y' || answer.toLowerCase() === 'yes') {
            setupEnv();
        } else {
            console.log('✅ Keeping existing .env file');
            rl.close();
        }
    });
} else {
    setupEnv();
}

function setupEnv() {
    console.log('\n🔑 OpenAI API Key Setup');
    console.log('Get your API key from: https://platform.openai.com/api-keys');
    console.log('Your API key should start with "sk-"\n');
    
    rl.question('Enter your OpenAI API key: ', (apiKey) => {
        if (!apiKey.trim()) {
            console.log('❌ No API key provided');
            rl.close();
            return;
        }
        
        if (!apiKey.startsWith('sk-')) {
            console.log('⚠️  Warning: API key should start with "sk-"');
        }
        
        // Create .env file
        const envContent = `# OpenAI API Key for Tunnl.ai Extension
# Generated by setup-env.js
OPENAI_API_KEY=${apiKey.trim()}
`;
        
        try {
            fs.writeFileSync(envPath, envContent);
            console.log('✅ .env file created successfully');
            console.log('🔧 The extension will now use this API key automatically');
            console.log('📝 You can edit .env file manually if needed');
        } catch (error) {
            console.error('❌ Error creating .env file:', error.message);
        }
        
        rl.close();
    });
}

rl.on('close', () => {
    console.log('\n🎉 Setup complete!');
    console.log('💡 Tip: Add .env to your .gitignore to keep your API key secure');
    process.exit(0);
});
